# Generated by Django 5.1.1 on 2024-10-01 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0005_alter_student_phone_number'),
        ('my_admin_app', '0002_remove_guide_date_remove_student_date_alter_date_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedguide',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin_app.guide'),
        ),
        migrations.AlterField(
            model_name='preferenceorder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin_app.student'),
        ),
        migrations.AlterField(
            model_name='allocatedguide',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin_app.student'),
        ),
        migrations.AlterField(
            model_name='preferenceorder',
            name='preference_order',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
