# Generated by Django 5.1.1 on 2024-10-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0006_alter_allocatedguide_guide_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllocatedGuide',
        ),
    ]
