# Generated by Django 5.1.1 on 2024-10-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
