# Generated by Django 5.0.1 on 2024-09-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_admin_app", "0002_remove_csvfile_uploaded_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvfile",
            name="file",
        ),
        migrations.AddField(
            model_name="csvfile",
            name="guide_file",
            field=models.FileField(
                default="uploads/default_guide.csv", upload_to="uploads/"
            ),
        ),
        migrations.AddField(
            model_name="csvfile",
            name="student_file",
            field=models.FileField(
                default="uploads/default_guide.csv", upload_to="uploads/"
            ),
        ),
    ]
