# Generated by Django 5.1.1 on 2024-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin_app', '0003_date_guide_file_name_date_student_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='allotment',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='allotment_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='cluster',
            field=models.IntegerField(default=0),
        ),
    ]
