# Generated by Django 5.1.1 on 2024-11-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin_app', '0004_student_allotment_student_allotment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='allotment',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
