# Generated by Django 5.1 on 2024-09-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferenceorder',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='student',
            name='eligibility',
        ),
        migrations.AddField(
            model_name='guide',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='guide_mail',
            field=models.EmailField(default='guide@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='preferenceorder',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='backlogs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='student@mail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
