# Generated by Django 5.1.1 on 2024-10-02 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo', '0001_initial'),
        ('my_admin_app', '0004_student_allotment_student_allotment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin_app.guide')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_admin_app.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
