# Generated by Django 5.1.1 on 2024-10-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=30)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pref_queue', models.JSONField(default=list)),
                ('cluster', models.IntegerField()),
                ('allotment_status', models.CharField(max_length=30)),
                ('allotment', models.CharField(max_length=30)),
            ],
        ),
    ]
