# Generated by Django 5.0.1 on 2024-09-28 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_admin_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="csvfile",
            name="uploaded_at",
        ),
    ]
